import type { GrammarTopic } from "../types.js";

export const perfekt: GrammarTopic = {
  id: "perfekt",
  level: "A2",
  order: 1,
  title: "Perfekt – a beszélt múlt idő",
  summary: "Hogyan meséld el, mi történt: haben vagy sein + Partizip II.",
  errorType: "Tempus",
  lesson: [
    {
      heading: "Mikor használjuk?",
      text: "A Perfekt a beszélt nyelv múlt ideje: szinte mindig ezt használjuk, ha arról mesélünk, mi történt. Két részből áll: a haben vagy a sein ragozott alakjából, amely a mondat 2. helyén áll, és az ige Partizip II alakjából, amely a mondat végére kerül.",
      examples: [
        { de: "Ich habe gestern Pizza gegessen.", hu: "Tegnap pizzát ettem." },
        { de: "Wir sind nach Wien gefahren.", hu: "Bécsbe utaztunk." },
      ],
    },
    {
      heading: "A Partizip II képzése",
      table: {
        headers: ["Igetípus", "Szabály", "Példa"],
        rows: [
          ["Szabályos ige", "ge- + tő + -t", "machen → gemacht, kaufen → gekauft"],
          ["Rendhagyó ige", "ge- + (gyakran megváltozó) tő + -en", "sehen → gesehen, trinken → getrunken"],
          ["Elváló igekötős ige", "igekötő + ge + tő + -t/-en", "einkaufen → eingekauft, anrufen → angerufen"],
          ["Nem elváló igekötős ige (be-, ver-, er-, ent-…)", "nincs ge-", "bezahlen → bezahlt, verstehen → verstanden"],
          ["-ieren végű ige", "nincs ge-", "studieren → studiert, telefonieren → telefoniert"],
        ],
      },
    },
    {
      heading: "haben vagy sein?",
      text: "A legtöbb ige a haben segédigét kapja. A sein segédigét kapják a helyváltoztatást jelentő igék (fahren, gehen, kommen, fliegen), az állapotváltozást jelentő igék (aufstehen, einschlafen, aufwachen), valamint a sein, a bleiben és a werden.",
      examples: [
        { de: "Ich bin um sieben Uhr aufgestanden.", hu: "Hétkor keltem fel." },
        { de: "Er ist zu Hause geblieben.", hu: "Otthon maradt." },
        { de: "Sie hat lange geschlafen.", hu: "Sokáig aludt." },
      ],
      tip: "Kérdezd meg magadtól: eljut-e valaki A-ból B-be, vagy megváltozik-e az állapota? Ha igen, sein kell. Az alvás (schlafen) nem változás, ezért haben, az elalvás (einschlafen) viszont igen, ezért sein.",
    },
  ],
  exercises: [
    {
      id: "p1",
      type: "choice",
      prompt: "Gestern ___ ich ins Kino gegangen.",
      options: ["habe", "bin", "hat"],
      answer: "bin",
      explanation: "A gehen helyváltoztatást jelent, ezért sein kell: ich bin gegangen.",
    },
    {
      id: "p2",
      type: "choice",
      prompt: "Wir ___ am Wochenende viel gearbeitet.",
      options: ["haben", "sind", "seid"],
      answer: "haben",
      explanation: "Az arbeiten nem mozgás és nem állapotváltozás, ezért haben: wir haben gearbeitet.",
    },
    {
      id: "p3",
      type: "choice",
      prompt: "Mein Bruder ___ nach Berlin geflogen.",
      options: ["hat", "ist", "sind"],
      answer: "ist",
      explanation: "A fliegen helyváltoztatás, ezért sein kell. Er alakban: er ist geflogen.",
    },
    {
      id: "p4",
      type: "choice",
      prompt: "___ du schon gefrühstückt?",
      options: ["Hast", "Bist", "Hat"],
      answer: "Hast",
      explanation: "A frühstücken haben segédigét kap, du alakban: du hast gefrühstückt.",
    },
    {
      id: "p5",
      type: "gap",
      prompt: "Ich habe gestern eine Pizza ___.",
      hint: "essen",
      answers: ["gegessen"],
      explanation: "Az essen rendhagyó ige: ge- + gess + -en → gegessen.",
    },
    {
      id: "p6",
      type: "gap",
      prompt: "Hast du schon die Rechnung ___?",
      hint: "bezahlen",
      answers: ["bezahlt"],
      explanation: "A be- nem elváló igekötő, ezért nincs ge-: bezahlt.",
    },
    {
      id: "p7",
      type: "gap",
      prompt: "Sie hat mich gestern Abend ___.",
      hint: "anrufen",
      answers: ["angerufen"],
      explanation: "Az an- elváló igekötő, a ge- közé kerül: an + ge + rufen → angerufen.",
    },
    {
      id: "p8",
      type: "gap",
      prompt: "Wir sind um sechs Uhr ___.",
      hint: "aufstehen",
      answers: ["aufgestanden"],
      explanation: "Elváló igekötős, rendhagyó ige: auf + ge + standen → aufgestanden. Állapotváltozás, ezért sein.",
    },
    {
      id: "p9",
      type: "gap",
      prompt: "Er hat drei Jahre in München ___.",
      hint: "studieren",
      answers: ["studiert"],
      explanation: "Az -ieren végű igék nem kapnak ge- előtagot: studiert.",
    },
    {
      id: "p10",
      type: "choice",
      prompt: "Das Kind ___ sofort eingeschlafen.",
      options: ["hat", "ist", "war"],
      answer: "ist",
      explanation: "Az einschlafen állapotváltozás (ébren → alszik), ezért sein: es ist eingeschlafen.",
    },
  ],
};
