import type { GrammarTopic } from "../types.js";

export const reflexiv: GrammarTopic = {
  id: "reflexiv",
  level: "A2",
  order: 9,
  title: "Visszaható igék: sich freuen, sich waschen",
  summary: "mich vagy mir? A visszaható névmás Akkusativban és Dativban.",
  errorType: "Kasus",
  lesson: [
    {
      heading: "Mi a visszaható ige?",
      text: "A visszaható ige cselekvése az alanyra irányul vissza: sich waschen (mosakodik), sich anziehen (felöltözik). A visszaható névmás (mich, dich, sich…) minden személyben ott van, és az alanyhoz igazodik. Sok igénél a magyarban nincs visszaható alak, a németben mégis kell a névmás: sich beeilen (siet), sich erinnern (emlékszik), sich freuen (örül).",
      table: {
        headers: ["", "Akkusativ", "Dativ"],
        rows: [
          ["ich", "mich", "mir"],
          ["du", "dich", "dir"],
          ["er / sie / es", "sich", "sich"],
          ["wir", "uns", "uns"],
          ["ihr", "euch", "euch"],
          ["sie / Sie", "sich", "sich"],
        ],
      },
      tip: "Csak az ich és a du alakban különbözik az Akkusativ és a Dativ. Harmadik személyben és a magázó Sie-nél mindig sich áll, kis kezdőbetűvel.",
    },
    {
      heading: "Mikor Dativ?",
      text: "Ha a mondatban van még egy Akkusativ tárgy is, a visszaható névmás Dativba kerül. Ich wasche mich: magamat mosom. Ich wasche mir die Hände: a kezemet mosom, itt a Hände az Akkusativ tárgy.",
      examples: [
        { de: "Ich ziehe mich an.", hu: "Felöltözöm." },
        { de: "Ich ziehe mir eine Jacke an.", hu: "Felveszek egy kabátot." },
        { de: "Wir freuen uns auf den Urlaub.", hu: "Várjuk a szabadságot." },
      ],
    },
    {
      heading: "Gyakori visszaható igék",
      table: {
        headers: ["Ige", "Jelentés"],
        rows: [
          ["sich freuen auf / über", "előre örül vminek / örül vminek"],
          ["sich beeilen", "siet"],
          ["sich erinnern an", "emlékszik vmire"],
          ["sich interessieren für", "érdeklődik vmi iránt"],
          ["sich ausruhen", "pihen"],
          ["sich treffen", "találkozik"],
          ["sich setzen", "leül"],
          ["sich ärgern über", "bosszankodik vmin"],
        ],
      },
      tip: "Kérdésben és fordított szórendben a névmás az alany után áll: Freust du dich? Heute ruhe ich mich aus.",
    },
  ],
  exercises: [
    {
      id: "r1",
      type: "choice",
      prompt: "Ich freue ___ auf das Wochenende.",
      options: ["mich", "mir", "sich"],
      answer: "mich",
      explanation: "Nincs más tárgy a mondatban, ezért Akkusativ: ich → mich.",
    },
    {
      id: "r2",
      type: "choice",
      prompt: "Wasch ___ bitte die Hände!",
      options: ["dich", "dir", "sich"],
      answer: "dir",
      explanation: "A die Hände az Akkusativ tárgy, ezért a visszaható névmás Dativba kerül: du → dir.",
    },
    {
      id: "r3",
      type: "gap",
      prompt: "Beeil ___, der Bus kommt!",
      hint: "du",
      answers: ["dich"],
      explanation: "A sich beeilen Akkusativot kér, du alakban: dich.",
    },
    {
      id: "r4",
      type: "choice",
      prompt: "Er interessiert ___ für Fußball.",
      options: ["ihn", "sich", "ihm"],
      answer: "sich",
      explanation: "Harmadik személyben a visszaható névmás mindig sich. Az ihn és az ihm valaki másra vonatkozna.",
    },
    {
      id: "r5",
      type: "gap",
      prompt: "Wir treffen ___ um acht Uhr vor dem Kino.",
      hint: "wir",
      answers: ["uns"],
      explanation: "sich treffen, wir alakban: uns.",
    },
    {
      id: "r6",
      type: "choice",
      prompt: "Ich ziehe ___ schnell eine Jacke an.",
      options: ["mich", "mir", "mein"],
      answer: "mir",
      explanation: "Az eine Jacke az Akkusativ tárgy, ezért a névmás Dativ: mir.",
    },
    {
      id: "r7",
      type: "gap",
      prompt: "Könnt ihr ___ an den Namen erinnern?",
      hint: "ihr",
      answers: ["euch"],
      explanation: "sich erinnern an, ihr alakban: euch.",
    },
    {
      id: "r8",
      type: "choice",
      prompt: "Setzen Sie ___ bitte!",
      options: ["Sie", "sich", "Ihnen"],
      answer: "sich",
      explanation: "A magázó Sie visszaható névmása is sich, kis kezdőbetűvel.",
    },
  ],
};
