import type { GrammarTopic } from "../types.js";

export const verbenMitPraepositionen: GrammarTopic = {
  id: "verben-praepositionen",
  level: "A2",
  order: 10,
  title: "Elöljárós igék: warten auf, denken an",
  summary: "Igék, amelyekhez fix elöljárószó tartozik, és a worauf / darauf alakok.",
  errorType: "Präposition",
  lesson: [
    {
      heading: "Fix elöljárók",
      text: "Sok német igéhez egy meghatározott elöljárószó tartozik, és ez gyakran nem egyezik a magyar raggal. A warten auf azt jelenti: vár valamire, a sich interessieren für pedig azt: érdeklődik valami iránt. Az elöljárót és az általa vonzott esetet az igével együtt érdemes megtanulni.",
      table: {
        headers: ["Ige", "Eset", "Jelentés", "Példa"],
        rows: [
          ["warten auf", "Akk.", "vár vkire/vmire", "Ich warte auf den Bus."],
          ["denken an", "Akk.", "gondol vkire/vmire", "Ich denke oft an dich."],
          ["sich freuen auf", "Akk.", "előre örül vminek", "Wir freuen uns auf den Urlaub."],
          ["sich freuen über", "Akk.", "örül vminek (ami megvan)", "Ich freue mich über das Geschenk."],
          ["sich interessieren für", "Akk.", "érdeklődik vmi iránt", "Er interessiert sich für Musik."],
          ["sich ärgern über", "Akk.", "bosszankodik vmin", "Sie ärgert sich über den Stau."],
          ["sprechen mit / über", "Dat. / Akk.", "beszél vkivel / vmiről", "Ich spreche mit ihm über das Problem."],
          ["fragen nach", "Dat.", "rákérdez vmire", "Er fragt nach dem Weg."],
          ["träumen von", "Dat.", "álmodik vmiről", "Ich träume von einem Haus am Meer."],
          ["teilnehmen an", "Dat.", "részt vesz vmin", "Sie nimmt an dem Kurs teil."],
        ],
      },
      tip: "sich freuen auf: valami jövőbelire örülsz előre (a szabadságra). sich freuen über: valaminek örülsz, ami már megvan vagy megtörtént (az ajándéknak).",
    },
    {
      heading: "Kérdés és utalás: wo(r)- és da(r)-",
      text: "Ha dologra kérdezünk, az elöljáró elé wo- kerül, ha dologra utalunk vissza, da-. Ha az elöljáró magánhangzóval kezdődik, egy -r- ékelődik be: auf → worauf / darauf, an → woran / daran, über → worüber / darüber. Mássalhangzónál nincs -r-: für → wofür / dafür, von → wovon / davon. Személyre viszont elöljáró + kérdőszó vagy névmás áll: Auf wen wartest du? – Auf ihn.",
      examples: [
        { de: "Worauf wartest du? – Auf den Bus.", hu: "Mire vársz? – A buszra." },
        { de: "Auf wen wartest du? – Auf meine Freundin.", hu: "Kire vársz? – A barátnőmre." },
        { de: "Ich freue mich schon darauf.", hu: "Már nagyon várom." },
      ],
    },
  ],
  exercises: [
    {
      id: "v1",
      type: "choice",
      prompt: "Ich warte schon seit einer Stunde ___ dich!",
      options: ["für", "auf", "an"],
      answer: "auf",
      explanation: "warten auf + Akkusativ: vár valakire.",
    },
    {
      id: "v2",
      type: "choice",
      prompt: "Er interessiert sich ___ Geschichte.",
      options: ["für", "an", "über"],
      answer: "für",
      explanation: "sich interessieren für: érdeklődik valami iránt.",
    },
    {
      id: "v3",
      type: "choice",
      prompt: "Denkst du noch ___ unseren Urlaub?",
      options: ["von", "auf", "an"],
      answer: "an",
      explanation: "denken an + Akkusativ: gondol valamire.",
    },
    {
      id: "v4",
      type: "gap",
      prompt: "Wir freuen uns schon ___ die Ferien nächste Woche.",
      hint: "előre örülünk",
      answers: ["auf"],
      explanation: "Jövőbeli dolognak előre örülni: sich freuen auf.",
    },
    {
      id: "v5",
      type: "choice",
      prompt: "Ich habe mich sehr ___ dein Geschenk gefreut.",
      options: ["auf", "über", "für"],
      answer: "über",
      explanation: "Az ajándék már megvan, ezért sich freuen über.",
    },
    {
      id: "v6",
      type: "choice",
      prompt: "___ wartest du? – Auf den Zug.",
      options: ["Worauf", "Wofür", "Woran"],
      answer: "Worauf",
      explanation: "Dologra kérdezünk: wo + r + auf → worauf.",
    },
    {
      id: "v7",
      type: "gap",
      prompt: "Er fragt den Polizisten ___ dem Weg.",
      hint: "rákérdez",
      answers: ["nach"],
      explanation: "fragen nach + Dativ: rákérdez valamire.",
    },
    {
      id: "v8",
      type: "choice",
      prompt: "Mit ___ hast du gestern telefoniert? – Mit meiner Schwester.",
      options: ["wem", "wen", "was"],
      answer: "wem",
      explanation: "Személyre kérdezünk, ezért elöljáró + kérdőszó. A mit Dativot kér: mit wem?",
    },
    {
      id: "v9",
      type: "gap",
      prompt: "Sie ärgert sich ___ den langen Stau.",
      hint: "bosszankodik vmin",
      answers: ["über"],
      explanation: "sich ärgern über + Akkusativ: bosszankodik valamin.",
    },
  ],
};
